server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /chat-app

spring:
  profiles:
    active: ${ACTIVE_PROFILE}

  application:
    name: chat-app

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

otp:
  mobile:
    api: ${OTP_MOBILE_API}
    senderId: ${SENDER_ID}

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
