server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /chat-app

spring:
  profiles:
    active: ${ACTIVE_PROFILE}

  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_USER_NAME}
    password: ${MQ_PASSWORD}
    virtual-host: ${MQ_VHOST}
    ssl:
      enabled: true

  application:
    name: chat-app

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

otp:
  mobile:
    api: ${OTP_MOBILE_API}
    senderId: ${SENDER_ID}

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

chat:
  relay:
    host: ${MQ_HOST}
    port: 61613 # STOMP over TLS
    login: ${MQ_USER_NAME}
    passcode: ${MQ_PASSWORD}
    virtual-host: ${MQ_VHOST}
