spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: validate   # never use 'update' in prod, only 'validate' or 'none'
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: ${DB_DIALECT}

  # Connection pool settings
  datasource.hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    idle-timeout: 30000
    pool-name: HikariCP
    max-lifetime: 1800000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
