server:
  port: ${SERVER_PORT}

spring:
  application:
    name: chat-app

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

otp:
  mobile:
    api: ${OTP_MOBILE_API}
    senderId: ${SENDER_ID}

jwt:
  secret: ${JWT_SECRET}

